<?php 
require 'vendor\autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;


$pdo = new PDO('mysql:host=localhost;port=3306;dbname=solars','root','');
$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
if (isset($_POST['submit']) && !empty($_POST['name'])  && !empty($_POST['email']) && !empty($_POST['phone']) && !empty($_POST['subject']) && !empty($_POST['message'])) {
    $name=  $_POST['name'];
    $email= $_POST['email'] ;
    $phone=  $_POST['phone'];
    $subject=  $_POST['subject'];
    $message= $_POST['message'];


    $mail = new PHPMailer();
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'jaydlampy@yahoo.co.uk'; //paste one generated by Mailtrap
    $mail->Password = 'feyisitan'; //paste one generated by Mailtrap
    $mail->SMTPSecure = 'tls';
    $mail->Port = 2525;
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;
    $v= $mail->SMTPDebug;
    
    $mail->setFrom("$email", "$name"); //sender
    //$mail->addReplyTo('tome@example.com', 'muyiwa'); 
    $mail->addAddress('jaydlampy@yahoo.co.uk', 'feyi'); //receiver
    $mail->Subject = "$subject";
    $mail->isHTML(true);
    $mailContent = "$message";
    $mail->Body = $mailContent;
    
    if($mail->send()){
        echo 'Message has been sent';
    }else{
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        echo"$v";
        
    }
}

  